include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_final_fields: true
    unnecessary_this: true
    always_declare_return_types: true
    avoid_empty_else: true
    avoid_relative_lib_imports: true
    avoid_shadowing_type_parameters: true
    avoid_types_as_parameter_names: true
    curly_braces_in_flow_control_structures: true
    empty_catches: true
    no_duplicate_case_values: true
    unrelated_type_equality_checks: true
    valid_regexps: true
